### ISSUE TITLE
Issues when running the script

### ISSUE THREAD

**Issue by Odanodlam** [tjarrettveracode/veracode-pipeline-mitigation#3]
We are facing issues when we call the script vcpipemit.py, having issues when importing the name parse.

[2021-07-05T17:56:49.995Z] + python vcpipemit.py -a xxx-xxxxxx-xxxxxx-xxxxx
[2021-07-05T17:56:50.417Z] Traceback (most recent call last):
[2021-07-05T17:56:50.417Z]   File "vcpipemit.py", line 8, in <module>
[2021-07-05T17:56:50.417Z]     from urllib import parse
[2021-07-05T17:56:50.417Z] ImportError: cannot import name parse

What should we do in this case?

Thanks

**Comment by tjarrettveracode** [comment]
Hi @Odanodlam , what version of Python are you using? The script is tested with recent versions of Python3. Also -- you may want to check which version of `urllib` you have in the local environment and make sure you've installed the version tested with the script, which you'll find in `requirements.txt`.

**Comment by Odanodlam** [comment]
Hi @tjarrettveracode , we are using python 3.7 with pip 19.2.3. For urllib it seems that we have installed urllib 3, still to be confirmed. 
With these tools, should the script work?

**Comment by tjarrettveracode** [comment]
They should -- so I'm not sure why you're getting a warning. For reference, my local development machine is on Python 3.9 with urllib3 1.26.6. 

I can see if we can reference the import a different way to avoid the error.

**Comment by Odanodlam** [comment]
Thanks @tjarrettveracode , I've confirmed, we are using the urllib3.

**Comment by Odanodlam** [comment]
Hello @tjarrettveracode, do you have any update about this topic? Can I try to run the script again?

**Comment by tjarrettveracode** [comment]
Hi @Odanodlam -- you should be able to use this if you are using Python 3 and urllib3. Can you please try re-running `pip install -r requirements.txt` and paste the output you're seeing here, and let me know if you are still having issues?

**Comment by Odanodlam** [comment]
Hello @tjarrettveracode , we are still facing the same issues as you can see on the txt attached. Should we upgrade the pip version for the newest?
[baselinefile.txt](https://github.com/tjarrettveracode/veracode-pipeline-mitigation/files/7106938/baselinefile.txt)

**Comment by Odanodlam** [comment]
Hey @tjarrettveracode did this log file help to try to understand the error we are getting?

**Comment by tjarrettveracode** [comment]
Taking a look at this, I see two things of note:

1. The version of `pip` that is installed is older;  however, the dependencies seem to have installed successfully so that may be a red herring.
2. Though the image says `python3` the command line that is called is just `python` -- is there a way that we can verify the python version with something like `python --version` so we can be absolutely sure what version of Python is invoked?

**Comment by Odanodlam** [comment]
Hello @tjarrettveracode pfa the log containing the required information.
[logbaseline.txt](https://github.com/tjarrettveracode/veracode-pipeline-mitigation/files/7198109/logbaseline.txt)

**Comment by tjarrettveracode** [comment]
Hi @Odanodlam , I think the import of `parse` ultimately proved to be unnecessary. Please try again with the latest version.

**Comment by Odanodlam** [comment]
Hello @tjarrettveracode ! 
the new version worked, but now we are facing issues when trying to get the information from the application.
we noticed that the argument that we need to use is applicationguid and after debugging it, we noticed that is a 32 character information. But we don't know what is this information. Where should we get this info?
Below the response we are receiving:

24/09/2021 09:29:45  + python3 vcpipemit.py -a sboot-arqt-base-atom-validation -rf ./resultsVeracode.json
24/09/2021 09:29:46  xxxx-xxxx-xxxx-xxxx-xxxxx is an invalid application guid. Please supply a valid UUID.

Thanks,

**Comment by tjarrettveracode** [comment]
You can use the /applications endpoint to get the required UUID: https://help.veracode.com/r/c_apps_intro

But you can also use the `--prompt` argument to identify the application by name if you're running the script interactively.
